name: Render and Commit README

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  render_and_commit:
    
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Render and Commit README

    runs-on: ubuntu-latest

    steps:
        
      - name: Installing quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.553/quarto-1.4.553-linux-amd64.deb
          sudo apt install ./quarto-1.4.553-linux-amd64.deb
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://packagemanager.posit.co/cran/latest"))
          install.packages(c("yaml", "rmarkdown"))
        shell: Rscript --vanilla -e {0}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render README
        run: |
          quarto render README.qmd --to gfm

      - name: Commit changes
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add README.md || echo "No changes to commit"
          git commit -m "Render README [skip ci]" || echo "No changes to commit"
          git push origin ${{ github.head_ref || github.ref_name }} || echo "No changes to push"
